image: node:14

pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - node_modules/@angular/cli/bin/ng build
          artifacts:
          - dist/**
      - step:
          name: Publish
          deployment: Production
          caches:
            - node
          script:
            - ssh -p1088 -oStrictHostKeyChecking=no eneasys@cpanel.sm-host.com "rm -rf api-gest.eneasys.com/public_html"
            - scp -P1088 -r dist/public_html/ eneasys@cpanel.sm-host.com:api-gest.eneasys.com/public_html
    develop:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - node_modules/@angular/cli/bin/ng build
          artifacts:
          - dist/**
      - step:
          name: Publish
          deployment: staging
          caches:
            - node
          script:
            - ssh -p1088 -oStrictHostKeyChecking=no eneasys@cpanel.sm-host.com "rm -rf api-gest.stage.eneasys.com/public_html"
            - scp -P1088 -r dist/public_html/ eneasys@cpanel.sm-host.com:api-gest.stage.eneasys.com/public_html
