/**
 * entityManager
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ResponsePersonDTO { 
    bornCityId?: number;
    bornCityName?: string;
    bornDate: string;
    firstname: string;
    id?: number;
    lastname: string;
    sex: ResponsePersonDTO.SexEnum;
}
export namespace ResponsePersonDTO {
    export type SexEnum = 'MALE' | 'FEMALE';
    export const SexEnum = {
        MALE: 'MALE' as SexEnum,
        FEMALE: 'FEMALE' as SexEnum
    };
}