/**
 * entityManager
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { ResponseEopooTypeDTO } from './responseEopooTypeDTO';
import { ResponseGenericEopooDTO } from './responseGenericEopooDTO';
import { ResponsePersonDTO } from './responsePersonDTO';


export interface ResponseEopooDTO { 
    eopooType?: ResponseEopooTypeDTO;
    eopooTypeId?: number;
    genericEopoo?: ResponseGenericEopooDTO;
    genericEopooId?: number;
    id?: number;
    person?: ResponsePersonDTO;
    personId?: number;
    taxNumber: string;
}